### ISSUE TITLE
Can launch IDBac, but repeatedly crashes

### ISSUE THREAD

**Issue by grimcynthia** [chasemc/IDBacApp#115]
Every time I launch IDBac it crashes by the screen turning gray. Most of the time I can't get past the launch screen, but the furthest I've gotten was to converting the Bruker data. I've gone into the task manager to check that I've ended any R processes in between launches, and I made sure to uninstall the old IDBac before installing the new one. I have Proteowizard 3.0.19014 installed, and have tried restarting my machine. One thing I didn't do was restart in between uninstalling the old version and reinstalling the new version.

Any new suggestions would be appreciated! :)

**Comment by chasemc** [comment]
Thanks for filling out the description. I'll be working through the next few days to figure out some of the issues the have arisen in the new version and will try and collaborate over the next couple weeks if needed to find the solution to why some users are having issues.

**Comment by chasemc** [comment]
In progress...
https://github.com/chasemc/electricShine/commit/fe2492a00025a961539c01edaa4f6a9d7a5725fa

**Comment by chasemc** [comment]
Fixed in https://github.com/chasemc/IDBacApp/commit/caf9623dfec3454da2dfacb8a181b38cf7f2ef05

**Comment by chasemc** [comment]
Also see #119
