### ISSUE TITLE
Raw Data Conversion Not Operating

### ISSUE THREAD

**Issue by synaptjacket** [chasemc/IDBacApp#124]
Hello, I'm really interested in using IDBac for some rapid ID of some of our biological samples, but I've been having a problem with the practice set of data so I can learn how to use the software. 

I've been using the example data set "bruker_autoflex.zip". After extracting the data to a new folder (filepath without any spaces), I try to convert the Bruker files. I select both the protein and small molecule data folder when processing the data. I also am able to fill the spreadhsheet and all the samples are labeled. 

After I click "Process Data", I'm stuck with the following window:

> "Important message
> IDBac is converting your Bruker files to open-source mzML, during this step there is no progress bar.
> After this step IDBac will begin to convert your files into an IDBac experiment."

Nothing happens (I've waited over an hour for the data to process) and the software seems to be frozen. I check task manager and the software is just sitting in memory utilizing none of the CPU. 

From a previous post (Unable to convert raw data. #11, Dec 5, 2017), I followed the troubleshooting protocol , but I'm still having the same problem. Below are some of the results for the troubleshooting steps.

1.) Is the working directory the "IDBac Data Storage Location"? I left this at the default and the raw data files are located in the following path:
C:\IDBac\Import_Raw_Data\IDBac_practice_autoflex_raw

Just in case, my "IDBac Data Storage Location" is located in the following path:
C:/Users/Stephen Zambrzycki/AppData/Local/Programs/IDBac

2.) 64bit (Windows 10 Home)

3.) I tested proteowizard and it works. I was able to get the "thermo_file.mzXML" file in "Output_Folder". 

I used the mzXML practice data set and the software works "mzxml.zip". Thanks for any help!

Stephen Zambrzycki
Graduate Research Assistant
Dr. Facundo M. Fernández's Lab
School of Chemistry and Biochemistry 
Georgia Institute of Technology

> Thanks for your patience working through this!
> 
> Last night I installed and successfully ran IDBac on a clean-install of windows, so I think something funky is going on.
> 
> Things to consider, from Easy to Hard:
> 
> 1. I know I already suggested this, but check again the entire file-path of your raw data and where you select the IDBac working directory. If there is a space anywhere, msconvert will get mad.
>    
>    * eg " file path -> C:\Users\chase\Documents\New Folder\Data" will fail because of the space "New folder"
> 2. Are you running 64bit or 32bit Windows?
>    If you're unsure, you can check here:
>    https://support.microsoft.com/en-us/help/15056/windows-7-32-64-bit-faq
>    
>    * If you are running 32bit, please stop here and respond.  I overlooked the necessity of this before, but we may need 32 & 64 bit versions of IDBac.
> 3. Proteowizard can be finicky, so that would be the next check. You can use a tool Ming and I wrote for GNPS.
> 
> * The download and instructions can be found under "Data Conversion-Easy".
>   https://bix-lab.ucsd.edu/display/Public/Data+Conversion+to+GNPS+Compatible+Formats+-+.mzXML+and+.mzML
>   
>   * After downloading, unzip the folder and Double-click the "Double-Click_To-Convert" file.  A command window should appear, once it disappears there should be a "thermo_file.mzXML" file in "Output_Folder".
> * If this doesn't work it means your computer is missing some service packs Proteowizard requires to function. They can be installed using that same GNPS tool:
> 
> > Install windows libraries in "pwizLibraries-and-Installation" - Run appropriate program for 32-bit (32-Bit_Double-Click_To_Install.bat) or 64-bit system (64-Bit_Double-Click_To_Install.bat). To find out which type of OS you have please check here .
> 
> 1. Upload your data folder to:
>    https://drive.google.com/drive/folders/1C1FEw5xCXjnT0unSUxZ86Wa7fGXlvcrG?usp=sharing
>    -This link will be taken down after I download

**Comment by chasemc** [comment]
Thanks for looking through the other issues first!

This is obviously a priority problem to figure out so I downloaded and installed IDBac and proteowizard on a fresh install of Windows and (unfortunately?) the conversion did work.   And just to note, the example data should take less than 5 min (likely much, much less, depending on your computer).

There are a couple of possibilities we can work through:

If you try and convert again, while it is "frozen" navigate to 
`C:/Users/Stephen Zambrzycki/AppData/Local/Programs/IDBac`

and see if there is a folder called `temp_mzML`
`C:/Users/Stephen Zambrzycki/AppData/Local/Programs/IDBac/temp_mzML`

Are there any `.mzML` files inside?


Also there is a bug (#125) in the spreadsheet input that I'll fix in the next update that causes "No missing ID's" to be displayed when there are missing ID's.  Fill in the entire spreadsheet with anything, and see if it converts. 


Let me know how this goes, and I'll hopefully have more insight to where your problem is occurring.

**Comment by synaptjacket** [comment]
Hey Chase, thanks for responding back! 

I switched computers once I got admin access to download the software and everything is working with the training set of data on the lab computer. The lab computer has Windows 10 Enterprise and a 64 bit processor and took about a minute to process. 

The training set on the lab computer works with or without the filling in the blank values in the Sample-ID spreadsheet . 

Before I switched computers, I still tried to troubleshoot on my personal computer which was having the problem above, maybe it might be an issue with others who try to use the software. 

On my personal computer, the conversion did not work again with or without filling the blanks in the Sample-ID spreadsheet. I accessed the `temp_mzXML` folder and in either case there were no files either time when the software froze. 

It might be a permission issue or something with my personal computer. I remember I had issues with running Anaconda because the permissions were messed up on my personal computer. I tried to "Run as Adminstrator" IDBac, but that didn't work either. If you have any other ideas let me know. 

Thanks again for the help!

Stephen Zambrzycki

**Comment by chasemc** [comment]
As you said Proteowizard did convert when you tried it alone, and then didn't when IDBac tried, the call to Proteowizard is possibly getting blocked by your firewall or antivirus. 

I'll try and work on something to catch this #126

What version of IDBac do you have?  Should be on page that's displayed when you open the app.

**Comment by synaptjacket** [comment]
I have IDBac version `1.1.10`

**Comment by chasemc** [comment]
Thanks @synaptjacket. I'm closing old issues and this one seems to mostly be resolved as you got it working on another computer (it would be impossible right now to debug).  
The next release (1.1.11) will support error logging (https://github.com/chasemc/electricShine/pull/74/commits/c43840d5cea63c42e55ac55026c651d678dc7c19) that will help me identify the issue if you run into this problem in the future.

**Comment by grimcynthia** [comment]
Just a heads up- I thought I was having this same issue with my own dataset until I peeked at the files and noticed not all of my small molecule data copied over. I figured it out when I went to convert manually with MSConvert, but thought I'd log it if other people run into this in the future.
