### ISSUE TITLE
Small Molecule MAN only appears for some samples when dealing with 2 experiments

### ISSUE THREAD

**Issue by grimcynthia** [chasemc/IDBacApp#129]
I'm using two experiments combined and trying to scroll through pieces of the dendrogram to view the various networks. I'm having issues viewing most of my samples on a MAN, excluding about a handful. I've tried moving a pre-existing box on the dendrogram, or closing out a box and then making a new box somewhere else on the dendrogram to no avail. Both experiments I've added have small molecule and protein data for all samples.

I retried viewing the MAN with each experiment separately and did not have any issues. When recombined, the same problem resurfaced. I tried this with both the default clustering settings and euclidian & ward.D2. I was able to track down one sample that was working and saw that it worked between both conditions.

![image](https://user-images.githubusercontent.com/50462434/61393837-6fb9a700-a887-11e9-8ae7-ca3a66ae2c82.png)
(well behaved samples)

![image](https://user-images.githubusercontent.com/50462434/61393864-806a1d00-a887-11e9-9640-7fc3d07e22d3.png)
(attempting to view a new network)

**Comment by chasemc** [comment]
Thanks @grimcynthia. We talked in person about this the other day, I just wanted to capture the gist of that conversation here for others. 

For now MANs can only display samples from the originally-selected "IDBac experiment", samples "injected" into the dendrogram will not show up.  I do think this would be a useful feature and will look into it.
