### ISSUE TITLE
Problems with combining experiments

### ISSUE THREAD

**Issue by grimcynthia** [chasemc/IDBacApp#131]
Hi Chase,

Two issues:
1. When trying to combine subsets of my experiments 1, 2, and 3 into mega-experiments "e.g. 1, 2, 3 Fungi and 1, 2, 3 Bacteria" I can only add, say, my subset from 1, and then when I try to add samples from 2 I can press the button to add the samples but no loading bar appears. I have to restart IDBac to add the next set. IDBac can also then crash on startup. I've tried using task manager to end associated processes to no avail, I've just been restarting my machine. I've tried doing this a couple times and I haven't been keeping track of how consistent every part of this is (Not loading the samples, then crashing when reloading IDBac) so your mileage may vary, but it's been popping up consistently.

2. When attempting to add metadata to one of my mega-experiments in a new column, it was saving for an indefinite amount of time. I ended up just closing out the program. The information was just a sequence of numbers, no spaces (20190705).

Thaaaaaanks :)
- Cynthia

**Comment by grimcynthia** [comment]
After my latest experiment combination, IDBac crashes on launch. I tried to reboot, then remove the last mega-experiment I made from the directory but no luck. Can send files via email if desired.

**Comment by chasemc** [comment]
Problem 1:  **Adding multiple experiments together.**  Is a known issue and there will be a fix in the upcoming release. 

Problem 2: **Crashing IDBac**, the next release will also have associated error logging to help me see what happened. Unfortunately I can't do much without that, but it might be related to problem 3

Problem 3: **Adding metadata and "Saving" seems to take forever** The "saving" screen should never take a long time to disappear as the process that is behind it doesn't take much time (never should be more than a minute or so).  This is a known bug, but is sporadic and right now a ghost of an issue.  If you can share the "mega-experiment" through google drive, and the version # of IDBac that would be awesome.

**Comment by chasemc** [comment]
RE: Issue 3  Is caused after adding a new column to the metaData table.  This will be fixed in the next version, but for now just avoid adding new columns
![image](https://user-images.githubusercontent.com/18691127/63528999-f3436500-c4d1-11e9-8289-e3d20f0e3fc1.png)
