### ISSUE TITLE
Crash on "Color by Dendrogram Labels"

### ISSUE THREAD

**Issue by grimcynthia** [chasemc/IDBacApp#135]
After coloring the dendrogram by height and then attempting to color the MAN by dendrogram labels, IDBac crashes.

Also happened without coloring the dendrogram first

**Comment by chasemc** [comment]
Can you send me your sqlite file? People are doing this a lot, so it might be something about the data that needs to be accounted for.

**Comment by chasemc** [comment]
I think this is probably due to a known bug. Re-open if different than: https://github.com/chasemc/IDBacApp/issues/136
