### ISSUE TITLE
IDBac does not load: "Error in evaluating the argument 'pool' in selecting a method for function 'poolCheckout'"

### ISSUE THREAD

**Issue by davidshumway** [chasemc/IDBacApp#149]
Installations of both the prioritizer and main branches are failing to load with the following error message:

```R
> install.packages("remotes") 
> remotes::install_github("chasemc/IDBacApp@*release")
# alternatively
> remotes::install_github("chasemc/IDBacApp@prioritizer")
> IDBacApp::run_app()
Loading required package: shiny

Listening on http://127.0.0.1:5554

Unfortunately msconvert is not currently available on this operating system, try again on Windows or start with 
               mzML or mzXML files instead of raw-data.
Warning: Error in <Anonymous>: error in evaluating the argument 'pool' in selecting a method for function 'poolCheckout': 
  71: <Anonymous>
Warning: Error in <Anonymous>: error in evaluating the argument 'pool' in selecting a method for function 'poolCheckout': 
  71: <Anonymous>
Warning: Error in <Anonymous>: error in evaluating the argument 'pool' in selecting a method for function 'poolCheckout': 
  71: <Anonymous>
Warning: Error in <Anonymous>: error in evaluating the argument 'pool' in selecting a method for function 'poolCheckout': 
  71: <Anonymous>
```

After this the browser window is accessible but goes "gray". The page is responsive and contains two tabs (Introduction and Starting with Raw Data) but no changes to the page can be made.

I believe this happens after a system upgrade on my end. I went from Fedora 31 to 33. In 31, the issue was not present. For some reason, it seems the newer operating system is causing some issue?

**Comment by chasemc** [comment]
Considering I'm reorganizing the IDBac R code and this is specifically a problem with an OS that isn't as widely used (and you said you were having issue with in developing the web app/database) I'm going to mark this as wontfix, if you figure out the problem let me know.
